apiVersion: v1
kind: Service
metadata:
  name: "service-albdemo"
  namespace: "alb-demo"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: "app-albdemo"
